### ISSUE TITLE
分享一下我的

### ISSUE THREAD

**Issue by yujincheng08** [Thiece/bilibili-safe#1]
<filters>
  <item enabled="true">u=59e46fd5</item>
  <item enabled="true">u=Dcba3f39</item>
  <item enabled="true">u=D036882b</item>
  <item enabled="true">u=7f86b8a2</item>
  <item enabled="true">u=6582eb8a</item>
  <item enabled="true">u=Da060d31</item>
  <item enabled="true">u=2332ac4b</item>
  <item enabled="true">u=D22ef1fa</item>
  <item enabled="true">u=353411e3</item>
  <item enabled="true">u=4b832df5</item>
  <item enabled="true">u=D6dd4047</item>
  <item enabled="true">u=91c40fe5</item>
  <item enabled="true">u=Dc88b64d</item>
  <item enabled="true">u=03dde896</item>
  <item enabled="true">u=Daf9ec7a</item>
  <item enabled="true">u=D26420d5</item>
  <item enabled="true">u=D4e7b038</item>
  <item enabled="true">u=D58bcf9f</item>
  <item enabled="true">u=D348066b</item>
  <item enabled="true">u=af82cd89</item>
  <item enabled="true">u=D63a47fd</item>
  <item enabled="true">u=D022439b</item>
  <item enabled="true">u=D49faaa1</item>
  <item enabled="true">u=7c649676</item>
  <item enabled="true">u=96e44c8c</item>
  <item enabled="true">u=64078b8a</item>
  <item enabled="true">u=db13597e</item>
  <item enabled="true">u=D48bf60c</item>
  <item enabled="true">u=0ecf66a4</item>
  <item enabled="true">u=</item>
  <item enabled="true">u=0bfc5b44</item>
  <item enabled="true">u=5f40886d</item>
  <item enabled="true">u=ff733f07</item>
  <item enabled="true">u=29aa4241</item>
  <item enabled="true">u=b98d968b</item>
  <item enabled="true">u=07d21bba</item>
  <item enabled="true">u=22755d59</item>
  <item enabled="true">u=4c43e24e</item>
  <item enabled="true">u=67a8e2fa</item>
  <item enabled="true">u=1963d87b</item>
  <item enabled="true">u=5c4f5307</item>
  <item enabled="true">u=1cf708f8</item>
  <item enabled="true">t=2B</item>
  <item enabled="true">u=9d440a1b</item>
  <item enabled="true">u=b4ae2cd0</item>
  <item enabled="true">u=2eb0098d</item>
  <item enabled="true">u=8af59c86</item>
  <item enabled="true">u=32cac22d</item>
  <item enabled="true">u=9a68640e</item>
  <item enabled="true">u=32281239</item>
  <item enabled="true">t=.avi</item>
  <item enabled="true">u=18949d93</item>
  <item enabled="true">u=6ed74a1d</item>
  <item enabled="true">t=by</item>
  <item enabled="true">u=绿字</item>
  <item enabled="true">u=c3bd8a06</item>
  <item enabled="true">u=08eb6cdc</item>
  <item enabled="true">u=f14b61f4</item>
  <item enabled="true">u=42f6c03c</item>
  <item enabled="true">u=9e4ecc12</item>
  <item enabled="true">u=e7fbcc8c</item>
  <item enabled="true">u=Daf8532e</item>
  <item enabled="true">u=7b81f359</item>
  <item enabled="true">t=ntr</item>
  <item enabled="true">u=12f92dbb</item>
  <item enabled="true">u=80763547</item>
  <item enabled="true">u=3cc045fa</item>
  <item enabled="true">u=e6173944</item>
  <item enabled="true">t=yooo</item>
  <item enabled="true">t=Yoooo</item>
  <item enabled="true">t=YOOOOO</item>
  <item enabled="true">u=07c2beb5</item>
  <item enabled="true">u=6549a07a</item>
  <item enabled="true">u=d99d0c99</item>
  <item enabled="true">u=716753b3</item>
  <item enabled="true">u=206b4e0d</item>
  <item enabled="true">u=e0d5d067</item>
  <item enabled="true">u=3be2e800</item>
  <item enabled="true">u=73f2a51e</item>
  <item enabled="true">u=87917442</item>
  <item enabled="true">t=SB</item>
  <item enabled="true">u=0cc9fde2</item>
  <item enabled="true">u=f3bc12b5</item>
  <item enabled="true">u=5cb26586</item>
  <item enabled="true">u=6c2e767e</item>
  <item enabled="true">u=ee40ebbb</item>
  <item enabled="true">u=9eea8f43</item>
  <item enabled="true">u=a77b3e96</item>
  <item enabled="true">u=22a78169</item>
  <item enabled="true">u=12f19ccb</item>
  <item enabled="true">u=4f5902e3</item>
  <item enabled="true">u=9fea07fd</item>
  <item enabled="true">u=aeda6d50</item>
  <item enabled="true">u=494ad86d</item>
  <item enabled="true">u=653eabdf</item>
  <item enabled="true">u=41b10d88</item>
  <item enabled="true">u=2ef389d7</item>
  <item enabled="true">u=6add1bb1</item>
  <item enabled="true">u=d95f1f3a</item>
  <item enabled="true">u=880d3c9c</item>
  <item enabled="true">u=d355bd91</item>
  <item enabled="true">u=b722061d</item>
  <item enabled="true">u=a89cd33a</item>
  <item enabled="true">u=cc9a4758</item>
  <item enabled="true">u=a3f727ca</item>
  <item enabled="true">u=cca78045</item>
  <item enabled="true">u=b1693031</item>
  <item enabled="true">u=06d8c9ec</item>
  <item enabled="true">u=aaa8c78c</item>
  <item enabled="true">u=5ac8a871</item>
  <item enabled="true">u=40e3f9c5</item>
  <item enabled="true">u=4ae1ca5a</item>
  <item enabled="true">u=d27c0749</item>
  <item enabled="true">u=bcbd82e3</item>
  <item enabled="true">u=dc550536</item>
  <item enabled="true">u=7a7d88ad</item>
  <item enabled="true">u=dfcadc4b</item>
  <item enabled="true">u=91136852</item>
  <item enabled="true">u=7bf0b1f0</item>
  <item enabled="true">u=3c1928d1</item>
  <item enabled="true">u=d6557acf</item>
  <item enabled="true">u=8275b669</item>
  <item enabled="true">u=6631a0c1</item>
  <item enabled="true">u=410d84ae</item>
  <item enabled="true">u=a74b1429</item>
  <item enabled="true">u=e98869ec</item>
  <item enabled="true">u=6d683721</item>
  <item enabled="true">t=^.$</item>
  <item enabled="true">t=飞</item>
  <item enabled="true">u=d475a157</item>
  <item enabled="true">u=dbb1c72f</item>
  <item enabled="true">u=e7ae7bd6</item>
  <item enabled="true">t=剧透</item>
  <item enabled="true">t=劇透</item>
  <item enabled="true">t=剧.?透</item>
  <item enabled="true">t=卡</item>
  <item enabled="true">t=巨人</item>
  <item enabled="true">t=兵长</item>
  <item enabled="true">t=龙门镖局</item>
  <item enabled="true">u=d739bd17</item>
  <item enabled="true">u=e77017ed</item>
  <item enabled="true">u=e8b4399d</item>
  <item enabled="true">u=1726b5e4</item>
  <item enabled="true">u=a00583ef</item>
  <item enabled="true">u=1bbc9e93</item>
  <item enabled="true">u=2d23ca6f</item>
  <item enabled="true">t=红字</item>
  <item enabled="true">t=中二</item>
  <item enabled="true">t=\n</item>
  <item enabled="true">t=透剧</item>
  <item enabled="true">t=团兵</item>
  <item enabled="true">t=兵长</item>
  <item enabled="true">t=艾伦</item>
  <item enabled="true">t=巨人</item>
  <item enabled="true">t=后颈</item>
  <item enabled="true">t=进击</item>
  <item enabled="true">t=腐女</item>
  <item enabled="true">t=伪腐</item>
  <item enabled="true">t=kaji</item>
  <item enabled="true">u=cdf04192</item>
  <item enabled="true">u=e30c0954</item>
  <item enabled="true">u=edc6edcc</item>
  <item enabled="true">u=968e7fcb</item>
  <item enabled="true">u=7a44f7e9</item>
  <item enabled="true">t=(.+)\1{3,}</item>
  <item enabled="true">u=2b4f55be</item>
  <item enabled="true">u=759c0624</item>
  <item enabled="true">t=抄袭</item>
  <item enabled="true">t=DNF</item>
  <item enabled="true">t=CF</item>
  <item enabled="true">t=SAO</item>
  <item enabled="true">t=刀剑</item>
  <item enabled="true">u=a4092fdb</item>
  <item enabled="true">t=dnf</item>
  <item enabled="true">u=72cf529b</item>
  <item enabled="true">u=baafe357</item>
  <item enabled="true">u=98d6d426</item>
  <item enabled="true">u=2055926e</item>
  <item enabled="true">u=0ec2041f</item>
  <item enabled="true">u=d845dce9</item>
  <item enabled="true">u=49f479cd</item>
  <item enabled="true">u=8d31aa17</item>
</filters>

**Comment by PlutoNameless** [comment]
能给我说下这个屏蔽用的的这些表单是在哪里找到的吗？还是你自己一点一点写的？

===============================================================================Infinite thinking, Endless masterpiece

Date: Sat, 19 Oct 2013 09:35:09 -0700
